### ISSUE TITLE
Callback URL appends characters preventing web-hook subscription on facebook

### ISSUE THREAD

**Issue by stigsfoot** [3sd/civicrm-chatbot#13]
I'm getting the following error when I provide the following URI - https://ict.demcloud.org/civicrm/chat/webhook/facebook

`The URL couldn't be validated. Response does not match challenge, expected value="1659010898", received="1659010898\u003C!DOCTYPE ..."`

![screen shot 2018-09-12 at 9 43 57 am](https://user-images.githubusercontent.com/573826/45429029-72001300-b670-11e8-915c-b8460b6b640b.png)

**Version**
CiviCRM 5.3.1.

**Comment by stigsfoot** [comment]
https://ict.demcloud.org/civicrm/chat/webhook/facebook?hub.mode=subscribe&hub.challenge=1109012784&hub.verify_token=da3bddc08fcf9f2f0786cd2d0b49485757e247798a74e238

**Comment by stigsfoot** [comment]
Message | Warning: Cannot modify header information - headers already sent by (output started at /var/aegir/platforms/demtools-civicrm-20180626/vendor/civicrm/civicrm-chatbot/vendor/symfony/http-foundation/Response.php:1276) in drupal_send_headers() (line 1490 of /var/aegir/platforms/demtools-civicrm-20180626/includes/bootstrap.inc).
-- | --

**Comment by stigsfoot** [comment]
QQ: How do we enable this as a packaged extension via Civi/Aegir? Feel free to close this issue after answering.

**Comment by michaelmcandrew** [comment]
Hey there,

I'm not sure how your Aegir set up works but I presume that you have some way of specifying a release to include in the build.

If so, this is the release that you should target: https://github.com/3sd/civicrm-chatbot/releases/tag/1.0.0-beta.2
